### ISSUE TITLE
callback function is 'not a function'?

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#176]
Hello,
I encountered an error when trying to use a callback function in AWS Lambda Authorizer.

Here is my implementation.
The authentication process has been excluded.

```
export const handler = async (event, context, callback) => {

  var authResponse = buildAllowAllPolicy(event, 'foo');
  callback(null, authResponse);
};

function buildAllowAllPolicy (event, principalId) {
  const policy = {
    principalId: principalId,
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: 'Allow',
          Resource: event.methodArn
        }
      ]
    }
  };
  return policy;
}
```
```
START RequestId: e50ca89a-72c6-436f-9534-9b7d9fe2cf99 Version: $LATEST
2024-02-19T13:34:52.844Z	e50ca89a-72c6-436f-9534-9b7d9fe2cf99	ERROR	    at handler (/var/task/index.mjs:4:3)
at startProcessEvents (@llrt/runtime:5:187)
2024-02-19T13:34:52.844Z	e50ca89a-72c6-436f-9534-9b7d9fe2cf99	ERROR	{
  errorType: 'TypeError',
  errorMessage: 'not a function',
  stackTrace: [ '    at handler (/var/task/index.mjs:4:3)', '    at startProcessEvents (@llrt/runtime:5:187)', '' ],
  requestId: 'e50ca89a-72c6-436f-9534-9b7d9fe2cf99'
}
END RequestId: e50ca89a-72c6-436f-9534-9b7d9fe2cf99
REPORT RequestId: e50ca89a-72c6-436f-9534-9b7d9fe2cf99	Duration: 1.71 ms	Billed Duration: 35 ms	Memory Size: 128 MB	Max Memory Used: 21 MB	Init Duration: 32.70 ms	
```

Do you know what could be the cause?

**Comment by nabetti1720** [comment]
Thank you for your quick response.
The problem has been resolved.

I have high expectations for this product.
