### ISSUE TITLE
React server module error

### ISSUE THREAD

**Issue by nmussy** [awslabs/llrt#241]
The LLRT React example:

https://github.com/awslabs/llrt/blob/84ed76f134ed4cb76c8bbb11831887e1a42ebc38/example/infrastructure/src/index.ts#L319-L328

throws the following error when `/llrt-react` is requested:

```
Error resolving module '/var/task/process' from 'stream'    at <anonymous> (stream:2:18087)
    at <anonymous> (stream:1:506)
    at <anonymous> (stream:2:75522)
    at <anonymous> (stream:1:506)
    at <anonymous> (stream:2:81273)
    at <anonymous> (stream:1:506)
    at <anonymous> (stream:2:82932)
    at <anonymous> (stream:1:506)
    at <anonymous> (stream:2:83196)
    at ../../node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js (/var/task/index.mjs:395:14)
    at __require2 (/var/task/index.mjs:18:17)
    at ../../node_modules/react-dom/server.node.js (/var/task/index.mjs:3849:11)
    at __require2 (/var/task/index.mjs:18:17)
    at <anonymous> (/var/task/index.mjs:4024:29)
```

Suspected regression caused by #167

_Originally posted by @nmussy in https://github.com/awslabs/llrt/pull/239#discussion_r1513856857_

**Comment by richarddavison** [comment]
This is the cause of the regression. They changed import to `process/` instead of `process`
https://github.com/nodejs/readable-stream/commit/b733ae549e674b639a2528ddfd5394b6b8bb9bb4
I'll see what we can do about this 🤔
