### ISSUE TITLE
`child_process.spawn.stdin` is a string instead of a function

### ISSUE THREAD

**Issue by guillaumefont** [awslabs/llrt#592]
Hi,

I"m trying to write to a processe created by `spawn` :

```js
const argon2 = spawn("argon2", [
  salt,
  `-p ${parallelism}`,
  `-m ${memory}`,
  `-t ${iterations}`,
  `-l ${length}`,
  "-id",
  "-e",
]);
argon2.stdin.write(password)
```

However I get the following error : 

```
2024-09-17T06:35:13.481Z	7fa3f84d-602c-41f7-919f-4b67b50b3b8d	ERROR	{
  errorType: 'TypeError',
  errorMessage: 'TypeError: not a function',
  stackTrace: '    at <anonymous> (/var/task/index.mjs:1:74177)
    at Promise (native)
    at Wn (/var/task/index.mjs:1:74057)
    at Hn (/var/task/index.mjs:1:75222)
    at Ia (/var/task/index.mjs:1:75624)
',
  requestId: '7fa3f84d-602c-41f7-919f-4b67b50b3b8d'
}
```

It seems like `stdin` is a string and not a function.

Thanks for your help !

**Comment by richarddavison** [comment]
Hi @guillaumefont, thanks for your comment. I think you might be looking at the wrong method call? Unfortunately QuickJS engine does not show the name of the function you're trying to execute. This is ofc something we plan to patch, but right know you would have to check the source manually.

```javascript
import { spawn } from "child_process";
const example = spawn("cat");
example.stdout.on("data", (d) => console.log(d.toString()));
example.stdin.write("hello world");
example.stdin.end();

```

**Comment by richarddavison** [comment]
Cool! I'll close for now, feel free to reopen if the issue persists!
