### ISSUE TITLE
Exports properties are not returned by require()

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#636]
While reading the Node.js package in the latest commit, I encountered a strange event.

```javascript
// main.js
const a = require('uuid')
console.log(a)
```

```
$ llrt main.js 
TypeError: not a function
  at <anonymous> (/home/ubuntu/llrt-test/node_modules/uuid/dist/commonjs-browser/./v3.js:10:10)
      at <anonymous> (/home/ubuntu/llrt-test/node_modules/uuid/./dist/commonjs-browser/index.js:96:34)
      at <anonymous> (main.js:1:11)
      at <anonymous> (eval_script:1:5)
```

While following the implementation and creating reproduction code, we found differences in behavior between Node.js and LLRT.

```javascript
// require1.js
Object.defineProperty(exports, "__esModule", {
  value: true
});

console.log("require1(__esModule): " + exports.__esModule);

exports.default = require1;

function require1(hello) {
  function helloWorld(world) {
    console.log(hello + ", " + world);
  }
  return helloWorld;
}
```

```javascript
// index1.js
var require1 = _interopRequireDefault(require("./require1.js"));
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }

console.log("index1(__esModule): " + require1.__esModule);

var greeting = (0, require1.default)('hello');
greeting('world');
```

It appears that the properties defined in Object.defineProperty() are not returned to the caller, causing the misclassification.
```
$ llrt index1.js 
require1(__esModule): true
index1(__esModule): undefined
TypeError: not a function
  at <anonymous> (index1.js:6:16)
      at <anonymous> (eval_script:1:5)

$ node index1.js 
require1(__esModule): true
index1(__esModule): true
hello, world
```

**Comment by nabetti1720** [comment]
At the very least, it can be referenced by the caller by modifying it as follows.
```javascript
// require1.js
Object.defineProperty(exports, "__esModule", {
  value: true,
  enumerable: true
});
...
```
```
$ llrt index1.js 
require1(__esModule): true
index1(__esModule): true
hello, world
```

However, I don't see why this would work in Node.js, since the spec says the initial value of [enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#enumerable) is `false`.

**Comment by nabetti1720** [comment]
It seems to be working by chance, but the essential cause may be different.

```javascript
// require1.js
Object.defineProperty(exports, "__esModule", {
  value: true
});

console.log(Object.getOwnPropertyDescriptor(exports, "__esModule"))
...
```
```
$ llrt index1.js 
{
  value: true,
  writable: false,
  enumerable: false,
  configurable: false
}
index1(__esModule): undefined
TypeError: not a function
  at <anonymous> (index1.js:6:16)
      at <anonymous> (eval_script:1:5)

$ node index1.js 
{
  value: true,
  writable: false,
  enumerable: false,
  configurable: false
}
index1(__esModule): true
hello, world
```
The behavior is different even though there is no difference between Node.js and LLRT in the state of the bool held as the initial value.

**Comment by richarddavison** [comment]
@nabetti1720 thanks for spotting! Great finding 🙌
