### ISSUE TITLE
LLRT with pg and ajv node_modules

### ISSUE THREAD

**Issue by rombat** [awslabs/llrt#670]
Hi,

I'd like to test LLRT on a lambda with only 2 node_modules: [pg](https://www.npmjs.com/package/pg)@8.13.1 and [Ajv](https://www.npmjs.com/package/ajv)@8.17.1

The version of LLRT I'm trying to use is this one: https://github.com/awslabs/llrt/releases/tag/v0.3.0-beta (llrt-lambda-arm64-no-sdk.zip)

Note: the lambda is working perfectly fine with node 20

I build the js with esbuild and this command (as recommended in the readme):
`esbuild index.mjs --platform=browser --target=es2020 --format=esm --bundle --minify --external:@aws-sdk --external:@smithy --outfile=output.js`
And I have the following errors:
```
X [ERROR] Could not resolve "events"

    node_modules/pg/lib/connection.js:3:27:
      3 │ var EventEmitter = require('events').EventEmitter
        ╵                            ~~~~~~~~

  The package "events" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

X [ERROR] Could not resolve "events"

    node_modules/pg-pool/index.js:2:29:
      2 │ const EventEmitter = require('events').EventEmitter
        ╵                              ~~~~~~~~

  The package "events" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

X [ERROR] Could not resolve "events"

    node_modules/pg/lib/client.js:3:27:
      3 │ var EventEmitter = require('events').EventEmitter
        ╵                            ~~~~~~~~

  The package "events" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

X [ERROR] Could not resolve "net"

    node_modules/pg/lib/connection.js:94:24:
      94 │       var net = require('net')
         ╵                         ~~~~~

  The package "net" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "--platform=node" to do that, which will remove this error.

X [ERROR] Could not resolve "events"

    node_modules/pg/lib/native/client.js:12:27:
      12 │ var EventEmitter = require('events').EventEmitter
         ╵                            ~~~~~~~~
  The package "events" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

X [ERROR] Could not resolve "net"

    node_modules/pg/lib/stream.js:22:24:
      22 │     const net = require('net')
         ╵                         ~~~~~

  The package "net" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "--platform=node" to do that, which will remove this error.

6 of 19 errors shown (disable the message limit with --log-limit=0)
node:child_process:929
    throw err;
    ^
```

I've tried to build it for node : 
`esbuild index.mjs --platform=node --target=es2020 --format=esm --bundle --minify --external:@aws-sdk --external:@smithy --outfile=output.js`

It builds without any issue, but the LLRT is still not working, i get runtime errors (the lambda only has the LLRT bootstrap file, and the built js file):
```json
{
    "time": "2024-11-08T09:48:31.331Z",
    "type": "platform.initStart",
    "record": {
        "initializationType": "on-demand",
        "phase": "init",
        "runtimeVersion": "provided:al2023.v40",
        "runtimeVersionArn": "arn:aws:lambda:eu-west-1::runtime:5bc9bdb449e3fab6f8bf362b27c618056398d62453b1b18704df69e8b2cc7c7b",
        "functionName": "REDACTED",
        "functionVersion": "$LATEST"
    }
},
{
    "time": "2024-11-08T09:48:31.390Z",
    "type": "platform.initRuntimeDone",
    "record": {
        "initializationType": "on-demand",
        "phase": "init",
        "status": "error",
        "errorType": "Runtime.ExitError"
    }
},
{
    "time": "2024-11-08T09:48:31.391Z",
    "type": "platform.initReport",
    "record": {
        "initializationType": "on-demand",
        "phase": "init",
        "status": "error",
        "errorType": "Runtime.ExitError",
        "metrics": {
            "durationMs": 59.381
        }
    }
},
{
    "time": "2024-11-08T09:48:31.408Z",
    "type": "platform.initStart",
    "record": {
        "initializationType": "on-demand",
        "phase": "invoke",
        "runtimeVersion": "provided:al2023.v40",
        "runtimeVersionArn": "arn:aws:lambda:eu-west-1::runtime:5bc9bdb449e3fab6f8bf362b27c618056398d62453b1b18704df69e8b2cc7c7b",
        "functionName": "axeptio-consents-reading-lambda-staging",
        "functionVersion": "$LATEST"
    }
},
{
    "time": "2024-11-08T09:48:31.408Z",
    "type": "platform.initStart",
    "record": {
        "initializationType": "on-demand",
        "phase": "invoke",
        "runtimeVersion": "provided:al2023.v40",
        "runtimeVersionArn": "arn:aws:lambda:eu-west-1::runtime:5bc9bdb449e3fab6f8bf362b27c618056398d62453b1b18704df69e8b2cc7c7b",
        "functionName": "REDACTED",
        "functionVersion": "$LATEST"
    }
},
{
    "time": "2024-11-08T09:48:32.136Z",
    "type": "platform.initRuntimeDone",
    "record": {
        "initializationType": "on-demand",
        "phase": "invoke",
        "status": "error",
        "errorType": "Runtime.ExitError"
    }
},
{
    "time": "2024-11-08T09:48:32.137Z",
    "type": "platform.initReport",
    "record": {
        "initializationType": "on-demand",
        "phase": "invoke",
        "status": "error",
        "errorType": "Runtime.ExitError",
        "metrics": {
            "durationMs": 728.857
        }
    }
},
{
    "time": "2024-11-08T09:48:32.137Z",
    "type": "platform.start",
    "record": {
        "requestId": "25590b72-ea61-45fc-a18b-6a2c0e2ac009",
        "version": "$LATEST",
        "tracing": {
            "spanId": "2d7707466d07f63d",
            "type": "X-Amzn-Trace-Id",
            "value": "Root=1-672dde6e-2e6d267a73743c9a4061b05c;Parent=1c8a5f7b62691196;Sampled=1"
        }
    }
},
{
    "time": "2024-11-08T09:48:32.175Z",
    "type": "platform.runtimeDone",
    "record": {
        "requestId": "25590b72-ea61-45fc-a18b-6a2c0e2ac009",
        "status": "error",
        "errorType": "Runtime.ExitError",
        "metrics": {
            "durationMs": 0,
            "producedBytes": 0
        }
    }
},
{
    "time": "2024-11-08T09:48:32.176Z",
    "type": "platform.report",
    "record": {
        "requestId": "25590b72-ea61-45fc-a18b-6a2c0e2ac009",
        "metrics": {
            "durationMs": 768.311,
            "billedDurationMs": 769,
            "memorySizeMB": 128,
            "maxMemoryUsedMB": 18
        },
        "tracing": {
            "spanId": "2d7707466d07f63d",
            "type": "X-Amzn-Trace-Id",
            "value": "Root=1-672dde6e-2e6d267a73743c9a4061b05c;Parent=1c8a5f7b62691196;Sampled=1"
        },
        "status": "error",
        "errorType": "Runtime.ExitError"
    }
}
```

Any idea how to fix this ?
Thanks in advance and have a nice day

**Comment by nabetti1720** [comment]
@rombat , We have reviewed the reported issues. There seem to be a few things that need to be resolved.

- The documentation is not clear enough about the build error with `--platform=browser`. First, LLRT does not support all Node.js APIs and is aimed at WinterCG compliance. In addition, some NPM packages may have prepared implementations for browsers, so we thought that specifying `--platform=browser` was likely to work. In this case, I think the correct approach is to specify `--platform=node`.

-  Regarding the `pg` package not working, I reproduced it on my laptop and got an error that the `dns` module, one of the built-in modules of Node.js, is not supported.

```javascript
// reproduction.js
const a = require('pg');
```
```
% ./node_modules/esbuild/bin/esbuild reproduction.js --platform=node --target=es2020 --format=esm --bundle --minify --external:@aws-sdk --external:@smithy --outfile=output.js 

  output.js  72.1kb

⚡ Done in 26ms

% llrt output.js 
ReferenceError: Error resolving module 'dns' from '/Users/shinya/Workspaces/llrt-test/output.js'
  at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:1:21727)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:1:448)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:2:2308)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:1:448)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:2:25748)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:1:448)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:2:26433)
``` 

- The `ajv` module not working seems to have a different cause. I tried to reproduce the same issue on my laptop and got a strange error.

```
// reproduction.js
const a = require('ajv');
```
```
% llrt output.js
SyntaxError: invalid escape sequence in regular expression
  at /Users/shinya/Workspaces/llrt-test/output.js:5:32981
```

I found the relevant section by directly executing `reproduction.js`.
```
% llrt reproduction.js 
SyntaxError: invalid escape sequence in regular expression
  at __cjs:/Users/shinya/Workspaces/llrt-test/node_modules/fast-uri/index.js:177:56
      at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/ajv/dist/runtime/uri.js:3:13)
      at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/ajv/dist/core.js:22:15)
      at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/ajv/dist/ajv.js:4:16)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/reproduction.js:1:11)
```

```javascript
// node_modules/fast-uri/index.js:177:56
const hexLookUp = Array.from({ length: 127 }, (v, k) => /[^!"$&'()*+,\-.;=_`a-z{}~]/u.test(String.fromCharCode(k)))
```

@richarddavison , Any comments would be appreciated. :)

**Comment by nabetti1720** [comment]
To digress a bit, we found the following problem during the verification.

```javascript
// reproduction.js
const a = require('pg');
```
```
% llrt reproduction.js
Error: IO Error: Is a directory (os error 21)
  at <anonymous> (/Users/shinya/Workspaces/llrt-test/reproduction.js:1:11)
```

I checked the package.json of the `pg` module and found a consideration leak.

package.json:
```json
{
  "main": "./lib",
}
```

In the case of such a description, we had to refer to `index.js` directly under that directory.

**Comment by nabetti1720** [comment]
After further verification, we found that the reason ajv does not work is in QuickJS and that this problem does not occur in QuickJS-NG. 

```javascript
// reproduction.js
const hexLookUp = Array.from({ length: 127 }, (v, k) => /[^!"$&'()*+,\-.;=_`a-z{}~]/u.test(String.fromCharCode(k)))
console.log(hexLookUp)
```

LLRT (main branch):
```
% llrt reproduction.js                                                                  
SyntaxError: invalid escape sequence in regular expression
  at /Users/shinya/Workspaces/llrt-test/reproduction.js:1:56
```

LLRT (quickjs-ng branch):
```
% ~/Workspaces/clone/llrt-clone/target/aarch64-apple-darwin/release/llrt reproduction.js
[ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false... 27 more items ]
```

We also confirmed that `const a = require(‘ajv’);` does not generate an error, although we did not paste the result. However, I have not been able to confirm the actual behavior.

**Comment by richarddavison** [comment]
ajv is likely to work but not pg as it require tls-sockets. We plan to support tls sockets eventually but there are a lot of other things depending on that first.
