### ISSUE TITLE
Crypto supported, but not.

### ISSUE THREAD

**Issue by paul-uz** [awslabs/llrt#757]
Docs state `crypto` is supported, but when I try to bundle some code that has a package using crypto, it errors

```
✘ [ERROR] Could not resolve "crypto"

    ../../node_modules/@opensearch-project/opensearch/lib/aws/shared.js:17:23:
      17 │ const crypto = require('crypto');
```

This is using 0.4.0

**Comment by nabetti1720** [comment]
I don't know which bundler you're using, but have you configured your bundler options to avoid bundling internal Node.js modules? If that option is not specified, the bundler will try to bundle Node.js modules as external packages and you may get an error like this one.

**Comment by paul-uz** [comment]
> I don't know which bundler you're using, but have you configured your bundler options to avoid bundling internal Node.js modules? If that option is not specified, the bundler will try to bundle Node.js modules as external packages and you may get an error like this one.

I'm using Esbuild. As far as I can tell I'm not doing anything with internal node modules. I'll post my config asap.

**Comment by richarddavison** [comment]
@paul-uz crypto is not a module but available in global scope. Remote the require and you’re good to go

**Comment by nabetti1720** [comment]
> @nabetti1720 i don’t think we expose this as a module. We should for compatibility sake!

@richarddavison , I apologize if my comment has caused misunderstanding. Most likely, this issue does not indicate a runtime error in LLRT, but rather an error occurring when creating a single app with the bundler.

Whether or not to make the crypto module public is another matter, but is this a suggestion for addressing this issue?

**Comment by gc-victor** [comment]
> I'm using Esbuild. As far as I can tell I'm not doing anything with internal node modules. I'll post my config asap.

Are you using `--platform=node`? I don't recall exactly what is the error message from esbuild when using crypto for browser

**Comment by gc-victor** [comment]
> Whether or not to make the crypto module public is another matte

It's already public. I have added it to my project yesterday.

**Comment by paul-uz** [comment]
> > I'm using Esbuild. As far as I can tell I'm not doing anything with internal node modules. I'll post my config asap.
> 
> Are you using `--platform=node`? I don't recall exactly what is the error message from esbuild when using crypto for browser 
> 

Nope, `browser` as shown in the docs.

**Comment by gc-victor** [comment]
> Nope, `browser` as shown in the docs.

Please, try with node, esbuild fails using crypto with browser as platform. I hope it fix the issue.

**Comment by paul-uz** [comment]
> > Nope, `browser` as shown in the docs.
> 
> Please, try with node, esbuild fails using crypto with browser as platform. I hope it fix the issue.

I tried, and I end up with errors like the one below

```
FATAL	TypeError: not a function
  at node_modules/debug/src/node.js (__cjs:/var/task/index.js:602:28)
      at __require2 (__cjs:/var/task/index.js:14:43)
      at node_modules/debug/src/index.js (__cjs:/var/task/index.js:771:24)
      at __require2 (__cjs:/var/task/index.js:14:43)
      at node_modules/@opensearch-project/opensearch/lib/Client.js (__cjs:/var/task/index.js:12352:17)
      at __require2 (__cjs:/var/task/index.js:14:43)
      at node_modules/@opensearch-project/opensearch/index.js (__cjs:/var/task/index.js:12603:31)
      at __require2 (__cjs:/var/task/index.js:14:43)
      at <anonymous> (__cjs:/var/task/index.js:13220:28)
```

**Comment by nabetti1720** [comment]
> I tried, and I end up with errors like the one below

I reproduced this on my laptop as follows (though the error line numbers are slightly different):
```javascript
// reproduction.js
const a = require('@opensearch-project/opensearch');
```
```
% npx esbuild reproduction.js --platform=node --target=es2023 --format=esm --bundle --external:@aws-sdk --external:@smithy > output.js

% llrt output.js
TypeError: not a function
  at node_modules/@opensearch-project/opensearch/node_modules/debug/src/node.js (/Users/shinya/Workspaces/llrt-test/output.js:599:28)
      at __require2 (/Users/shinya/Workspaces/llrt-test/output.js:9:42)
      at node_modules/@opensearch-project/opensearch/node_modules/debug/src/index.js (/Users/shinya/Workspaces/llrt-test/output.js:768:24)
      at __require2 (/Users/shinya/Workspaces/llrt-test/output.js:9:42)
      at node_modules/@opensearch-project/opensearch/index.js (/Users/shinya/Workspaces/llrt-test/output.js:11657:17)
      at __require2 (/Users/shinya/Workspaces/llrt-test/output.js:9:42)
      at <anonymous> (/Users/shinya/Workspaces/llrt-test/output.js:11925:9)
```

There are various reasons why a `TypeError: not a function` error may occur, but in this case it is likely due to the absence of a `deprecate` function in the `util` module.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/dcf51a4a-0466-403a-9045-fa20b5406e65" />

**Comment by paul-uz** [comment]
@nabetti1720 what are my options in this case then?

I'm desperate to use LLRT, but I fear its still a long way off :(

**Comment by nabetti1720** [comment]
@paul-uz, I did a quick search and `@opensearch-project/opensearch` is heavily dependent on standard Node.js modules (e.g. some functions in `util`, `https`, `http`, `streams` which are not web standards).

LLRT has `https` and `http` on its roadmap, but nothing else. It's possible that modules not on the roadmap will be supported in the future, but we don't know at this time.

I think the best solution at the moment is to continue using Node.js.

**Comment by richarddavison** [comment]
Sorry but the open search client is to dependent on Node.js APIs for now :(

**Comment by richarddavison** [comment]
Closing due to unsupported Node.js APIs
